ALTER TABLE [dbo].[carrot_SerialCache]
    ADD CONSTRAINT [carrot_SerialCache_PK] PRIMARY KEY CLUSTERED ([SerialCacheID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

