ALTER TABLE [dbo].[carrot_UserSiteMapping]
    ADD CONSTRAINT [carrot_UserSiteMapping_PK] PRIMARY KEY CLUSTERED ([UserSiteMappingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
