ALTER TABLE [dbo].[carrot_ContentTag]
    ADD CONSTRAINT [PK_carrot_ContentTag] PRIMARY KEY NONCLUSTERED ([ContentTagID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];
