#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrotware.CMS.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarrotwareCMS")]
	public partial class CarrotCMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaspnet_User(aspnet_User instance);
    partial void Updateaspnet_User(aspnet_User instance);
    partial void Deleteaspnet_User(aspnet_User instance);
    partial void Insertaspnet_Membership(aspnet_Membership instance);
    partial void Updateaspnet_Membership(aspnet_Membership instance);
    partial void Deleteaspnet_Membership(aspnet_Membership instance);
    partial void Insertaspnet_Role(aspnet_Role instance);
    partial void Updateaspnet_Role(aspnet_Role instance);
    partial void Deleteaspnet_Role(aspnet_Role instance);
    partial void Insertcarrot_UserSiteMapping(carrot_UserSiteMapping instance);
    partial void Updatecarrot_UserSiteMapping(carrot_UserSiteMapping instance);
    partial void Deletecarrot_UserSiteMapping(carrot_UserSiteMapping instance);
    partial void Insertcarrot_Content(carrot_Content instance);
    partial void Updatecarrot_Content(carrot_Content instance);
    partial void Deletecarrot_Content(carrot_Content instance);
    partial void Insertcarrot_Site(carrot_Site instance);
    partial void Updatecarrot_Site(carrot_Site instance);
    partial void Deletecarrot_Site(carrot_Site instance);
    partial void Insertcarrot_SerialCache(carrot_SerialCache instance);
    partial void Updatecarrot_SerialCache(carrot_SerialCache instance);
    partial void Deletecarrot_SerialCache(carrot_SerialCache instance);
    partial void Insertcarrot_Widget(carrot_Widget instance);
    partial void Updatecarrot_Widget(carrot_Widget instance);
    partial void Deletecarrot_Widget(carrot_Widget instance);
    partial void Insertcarrot_RootContent(carrot_RootContent instance);
    partial void Updatecarrot_RootContent(carrot_RootContent instance);
    partial void Deletecarrot_RootContent(carrot_RootContent instance);
    partial void Insertcarrot_WidgetData(carrot_WidgetData instance);
    partial void Updatecarrot_WidgetData(carrot_WidgetData instance);
    partial void Deletecarrot_WidgetData(carrot_WidgetData instance);
    #endregion
		
		public CarrotCMSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CarrotwareCMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarrotCMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrotCMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrotCMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarrotCMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<aspnet_User> aspnet_Users
		{
			get
			{
				return this.GetTable<aspnet_User>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_Membership> aspnet_Memberships
		{
			get
			{
				return this.GetTable<aspnet_Membership>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_Role> aspnet_Roles
		{
			get
			{
				return this.GetTable<aspnet_Role>();
			}
		}
		
		public System.Data.Linq.Table<carrot_UserSiteMapping> carrot_UserSiteMappings
		{
			get
			{
				return this.GetTable<carrot_UserSiteMapping>();
			}
		}
		
		public System.Data.Linq.Table<carrot_Content> carrot_Contents
		{
			get
			{
				return this.GetTable<carrot_Content>();
			}
		}
		
		public System.Data.Linq.Table<carrot_Site> carrot_Sites
		{
			get
			{
				return this.GetTable<carrot_Site>();
			}
		}
		
		public System.Data.Linq.Table<carrot_SerialCache> carrot_SerialCaches
		{
			get
			{
				return this.GetTable<carrot_SerialCache>();
			}
		}
		
		public System.Data.Linq.Table<carrot_Widget> carrot_Widgets
		{
			get
			{
				return this.GetTable<carrot_Widget>();
			}
		}
		
		public System.Data.Linq.Table<carrot_RootContent> carrot_RootContents
		{
			get
			{
				return this.GetTable<carrot_RootContent>();
			}
		}
		
		public System.Data.Linq.Table<carrot_WidgetData> carrot_WidgetDatas
		{
			get
			{
				return this.GetTable<carrot_WidgetData>();
			}
		}
		
		public System.Data.Linq.Table<vw_carrot_Content> vw_carrot_Contents
		{
			get
			{
				return this.GetTable<vw_carrot_Content>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
	public partial class aspnet_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _LoweredUserName;
		
		private string _MobileAlias;
		
		private bool _IsAnonymous;
		
		private System.DateTime _LastActivityDate;
		
		private EntityRef<aspnet_Membership> _aspnet_Membership;
		
		private EntitySet<carrot_UserSiteMapping> _carrot_UserSiteMappings;
		
		private EntitySet<carrot_Content> _carrot_Contents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
		
		public aspnet_User()
		{
			this._aspnet_Membership = default(EntityRef<aspnet_Membership>);
			this._carrot_UserSiteMappings = new EntitySet<carrot_UserSiteMapping>(new Action<carrot_UserSiteMapping>(this.attach_carrot_UserSiteMappings), new Action<carrot_UserSiteMapping>(this.detach_carrot_UserSiteMappings));
			this._carrot_Contents = new EntitySet<carrot_Content>(new Action<carrot_Content>(this.attach_carrot_Contents), new Action<carrot_Content>(this.detach_carrot_Contents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				if ((this._LoweredUserName != value))
				{
					this.OnLoweredUserNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredUserName = value;
					this.SendPropertyChanged("LoweredUserName");
					this.OnLoweredUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
		public string MobileAlias
		{
			get
			{
				return this._MobileAlias;
			}
			set
			{
				if ((this._MobileAlias != value))
				{
					this.OnMobileAliasChanging(value);
					this.SendPropertyChanging();
					this._MobileAlias = value;
					this.SendPropertyChanged("MobileAlias");
					this.OnMobileAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
		public bool IsAnonymous
		{
			get
			{
				return this._IsAnonymous;
			}
			set
			{
				if ((this._IsAnonymous != value))
				{
					this.OnIsAnonymousChanging(value);
					this.SendPropertyChanging();
					this._IsAnonymous = value;
					this.SendPropertyChanged("IsAnonymous");
					this.OnIsAnonymousChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_aspnet_Membership", Storage="_aspnet_Membership", ThisKey="UserId", OtherKey="UserId", IsUnique=true, IsForeignKey=false)]
		public aspnet_Membership aspnet_Membership
		{
			get
			{
				return this._aspnet_Membership.Entity;
			}
			set
			{
				aspnet_Membership previousValue = this._aspnet_Membership.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Membership.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Membership.Entity = null;
						previousValue.aspnet_User = null;
					}
					this._aspnet_Membership.Entity = value;
					if ((value != null))
					{
						value.aspnet_User = this;
					}
					this.SendPropertyChanged("aspnet_Membership");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_carrot_UserSiteMapping", Storage="_carrot_UserSiteMappings", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<carrot_UserSiteMapping> carrot_UserSiteMappings
		{
			get
			{
				return this._carrot_UserSiteMappings;
			}
			set
			{
				this._carrot_UserSiteMappings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_carrot_Content", Storage="_carrot_Contents", ThisKey="UserId", OtherKey="EditUserId")]
		public EntitySet<carrot_Content> carrot_Contents
		{
			get
			{
				return this._carrot_Contents;
			}
			set
			{
				this._carrot_Contents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrot_UserSiteMappings(carrot_UserSiteMapping entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_User = this;
		}
		
		private void detach_carrot_UserSiteMappings(carrot_UserSiteMapping entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_User = null;
		}
		
		private void attach_carrot_Contents(carrot_Content entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_User = this;
		}
		
		private void detach_carrot_Contents(carrot_Content entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Membership")]
	public partial class aspnet_Membership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _Password;
		
		private int _PasswordFormat;
		
		private string _PasswordSalt;
		
		private string _MobilePIN;
		
		private string _Email;
		
		private string _LoweredEmail;
		
		private string _PasswordQuestion;
		
		private string _PasswordAnswer;
		
		private bool _IsApproved;
		
		private bool _IsLockedOut;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _LastLoginDate;
		
		private System.DateTime _LastPasswordChangedDate;
		
		private System.DateTime _LastLockoutDate;
		
		private int _FailedPasswordAttemptCount;
		
		private System.DateTime _FailedPasswordAttemptWindowStart;
		
		private int _FailedPasswordAnswerAttemptCount;
		
		private System.DateTime _FailedPasswordAnswerAttemptWindowStart;
		
		private string _Comment;
		
		private EntityRef<aspnet_User> _aspnet_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordFormatChanging(int value);
    partial void OnPasswordFormatChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnMobilePINChanging(string value);
    partial void OnMobilePINChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoweredEmailChanging(string value);
    partial void OnLoweredEmailChanged();
    partial void OnPasswordQuestionChanging(string value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnIsApprovedChanging(bool value);
    partial void OnIsApprovedChanged();
    partial void OnIsLockedOutChanging(bool value);
    partial void OnIsLockedOutChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastLoginDateChanging(System.DateTime value);
    partial void OnLastLoginDateChanged();
    partial void OnLastPasswordChangedDateChanging(System.DateTime value);
    partial void OnLastPasswordChangedDateChanged();
    partial void OnLastLockoutDateChanging(System.DateTime value);
    partial void OnLastLockoutDateChanged();
    partial void OnFailedPasswordAttemptCountChanging(int value);
    partial void OnFailedPasswordAttemptCountChanged();
    partial void OnFailedPasswordAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAttemptWindowStartChanged();
    partial void OnFailedPasswordAnswerAttemptCountChanging(int value);
    partial void OnFailedPasswordAnswerAttemptCountChanged();
    partial void OnFailedPasswordAnswerAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAnswerAttemptWindowStartChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public aspnet_Membership()
		{
			this._aspnet_User = default(EntityRef<aspnet_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._aspnet_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFormat", DbType="Int NOT NULL")]
		public int PasswordFormat
		{
			get
			{
				return this._PasswordFormat;
			}
			set
			{
				if ((this._PasswordFormat != value))
				{
					this.OnPasswordFormatChanging(value);
					this.SendPropertyChanging();
					this._PasswordFormat = value;
					this.SendPropertyChanged("PasswordFormat");
					this.OnPasswordFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePIN", DbType="NVarChar(16)")]
		public string MobilePIN
		{
			get
			{
				return this._MobilePIN;
			}
			set
			{
				if ((this._MobilePIN != value))
				{
					this.OnMobilePINChanging(value);
					this.SendPropertyChanging();
					this._MobilePIN = value;
					this.SendPropertyChanged("MobilePIN");
					this.OnMobilePINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredEmail", DbType="NVarChar(256)")]
		public string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				if ((this._LoweredEmail != value))
				{
					this.OnLoweredEmailChanging(value);
					this.SendPropertyChanging();
					this._LoweredEmail = value;
					this.SendPropertyChanged("LoweredEmail");
					this.OnLoweredEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="NVarChar(256)")]
		public string PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				if ((this._PasswordQuestion != value))
				{
					this.OnPasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._PasswordQuestion = value;
					this.SendPropertyChanged("PasswordQuestion");
					this.OnPasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="NVarChar(128)")]
		public string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				if ((this._PasswordAnswer != value))
				{
					this.OnPasswordAnswerChanging(value);
					this.SendPropertyChanging();
					this._PasswordAnswer = value;
					this.SendPropertyChanged("PasswordAnswer");
					this.OnPasswordAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApproved", DbType="Bit NOT NULL")]
		public bool IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				if ((this._IsApproved != value))
				{
					this.OnIsApprovedChanging(value);
					this.SendPropertyChanging();
					this._IsApproved = value;
					this.SendPropertyChanged("IsApproved");
					this.OnIsApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit NOT NULL")]
		public bool IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordChangedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastPasswordChangedDate
		{
			get
			{
				return this._LastPasswordChangedDate;
			}
			set
			{
				if ((this._LastPasswordChangedDate != value))
				{
					this.OnLastPasswordChangedDateChanging(value);
					this.SendPropertyChanging();
					this._LastPasswordChangedDate = value;
					this.SendPropertyChanged("LastPasswordChangedDate");
					this.OnLastPasswordChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLockoutDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLockoutDate
		{
			get
			{
				return this._LastLockoutDate;
			}
			set
			{
				if ((this._LastLockoutDate != value))
				{
					this.OnLastLockoutDateChanging(value);
					this.SendPropertyChanging();
					this._LastLockoutDate = value;
					this.SendPropertyChanged("LastLockoutDate");
					this.OnLastLockoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAttemptCount
		{
			get
			{
				return this._FailedPasswordAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAttemptCount != value))
				{
					this.OnFailedPasswordAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAttemptCount");
					this.OnFailedPasswordAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAttemptWindowStart != value))
				{
					this.OnFailedPasswordAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAttemptWindowStart");
					this.OnFailedPasswordAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._FailedPasswordAnswerAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptCount != value))
				{
					this.OnFailedPasswordAnswerAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptCount");
					this.OnFailedPasswordAnswerAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAnswerAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAnswerAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptWindowStart != value))
				{
					this.OnFailedPasswordAnswerAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
					this.OnFailedPasswordAnswerAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_aspnet_Membership", Storage="_aspnet_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public aspnet_User aspnet_User
		{
			get
			{
				return this._aspnet_User.Entity;
			}
			set
			{
				aspnet_User previousValue = this._aspnet_User.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_User.Entity = null;
						previousValue.aspnet_Membership = null;
					}
					this._aspnet_User.Entity = value;
					if ((value != null))
					{
						value.aspnet_Membership = this;
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("aspnet_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Roles")]
	public partial class aspnet_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _RoleId;
		
		private string _RoleName;
		
		private string _LoweredRoleName;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnLoweredRoleNameChanging(string value);
    partial void OnLoweredRoleNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public aspnet_Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredRoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredRoleName
		{
			get
			{
				return this._LoweredRoleName;
			}
			set
			{
				if ((this._LoweredRoleName != value))
				{
					this.OnLoweredRoleNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredRoleName = value;
					this.SendPropertyChanged("LoweredRoleName");
					this.OnLoweredRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_UserSiteMapping")]
	public partial class carrot_UserSiteMapping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserSiteMappingID;
		
		private System.Guid _UserId;
		
		private System.Guid _SiteID;
		
		private EntityRef<aspnet_User> _aspnet_User;
		
		private EntityRef<carrot_Site> _carrot_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserSiteMappingIDChanging(System.Guid value);
    partial void OnUserSiteMappingIDChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    #endregion
		
		public carrot_UserSiteMapping()
		{
			this._aspnet_User = default(EntityRef<aspnet_User>);
			this._carrot_Site = default(EntityRef<carrot_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSiteMappingID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserSiteMappingID
		{
			get
			{
				return this._UserSiteMappingID;
			}
			set
			{
				if ((this._UserSiteMappingID != value))
				{
					this.OnUserSiteMappingIDChanging(value);
					this.SendPropertyChanging();
					this._UserSiteMappingID = value;
					this.SendPropertyChanged("UserSiteMappingID");
					this.OnUserSiteMappingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._aspnet_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					if (this._carrot_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_carrot_UserSiteMapping", Storage="_aspnet_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public aspnet_User aspnet_User
		{
			get
			{
				return this._aspnet_User.Entity;
			}
			set
			{
				aspnet_User previousValue = this._aspnet_User.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_User.Entity = null;
						previousValue.carrot_UserSiteMappings.Remove(this);
					}
					this._aspnet_User.Entity = value;
					if ((value != null))
					{
						value.carrot_UserSiteMappings.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("aspnet_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Site_carrot_UserSiteMapping", Storage="_carrot_Site", ThisKey="SiteID", OtherKey="SiteID", IsForeignKey=true)]
		public carrot_Site carrot_Site
		{
			get
			{
				return this._carrot_Site.Entity;
			}
			set
			{
				carrot_Site previousValue = this._carrot_Site.Entity;
				if (((previousValue != value) 
							|| (this._carrot_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrot_Site.Entity = null;
						previousValue.carrot_UserSiteMappings.Remove(this);
					}
					this._carrot_Site.Entity = value;
					if ((value != null))
					{
						value.carrot_UserSiteMappings.Add(this);
						this._SiteID = value.SiteID;
					}
					else
					{
						this._SiteID = default(System.Guid);
					}
					this.SendPropertyChanged("carrot_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_Content")]
	public partial class carrot_Content : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ContentID;
		
		private System.Guid _Root_ContentID;
		
		private System.Nullable<System.Guid> _Parent_ContentID;
		
		private System.Nullable<bool> _IsLatestVersion;
		
		private string _TitleBar;
		
		private string _NavMenuText;
		
		private string _PageHead;
		
		private string _PageText;
		
		private string _LeftPageText;
		
		private string _RightPageText;
		
		private System.Nullable<int> _NavOrder;
		
		private System.Nullable<System.Guid> _EditUserId;
		
		private System.DateTime _EditDate;
		
		private string _TemplateFile;
		
		private string _MetaKeyword;
		
		private string _MetaDescription;
		
		private EntityRef<aspnet_User> _aspnet_User;
		
		private EntityRef<carrot_RootContent> _carrot_RootContent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContentIDChanging(System.Guid value);
    partial void OnContentIDChanged();
    partial void OnRoot_ContentIDChanging(System.Guid value);
    partial void OnRoot_ContentIDChanged();
    partial void OnParent_ContentIDChanging(System.Nullable<System.Guid> value);
    partial void OnParent_ContentIDChanged();
    partial void OnIsLatestVersionChanging(System.Nullable<bool> value);
    partial void OnIsLatestVersionChanged();
    partial void OnTitleBarChanging(string value);
    partial void OnTitleBarChanged();
    partial void OnNavMenuTextChanging(string value);
    partial void OnNavMenuTextChanged();
    partial void OnPageHeadChanging(string value);
    partial void OnPageHeadChanged();
    partial void OnPageTextChanging(string value);
    partial void OnPageTextChanged();
    partial void OnLeftPageTextChanging(string value);
    partial void OnLeftPageTextChanged();
    partial void OnRightPageTextChanging(string value);
    partial void OnRightPageTextChanged();
    partial void OnNavOrderChanging(System.Nullable<int> value);
    partial void OnNavOrderChanged();
    partial void OnEditUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnEditUserIdChanged();
    partial void OnEditDateChanging(System.DateTime value);
    partial void OnEditDateChanged();
    partial void OnTemplateFileChanging(string value);
    partial void OnTemplateFileChanged();
    partial void OnMetaKeywordChanging(string value);
    partial void OnMetaKeywordChanged();
    partial void OnMetaDescriptionChanging(string value);
    partial void OnMetaDescriptionChanged();
    #endregion
		
		public carrot_Content()
		{
			this._aspnet_User = default(EntityRef<aspnet_User>);
			this._carrot_RootContent = default(EntityRef<carrot_RootContent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ContentID
		{
			get
			{
				return this._ContentID;
			}
			set
			{
				if ((this._ContentID != value))
				{
					this.OnContentIDChanging(value);
					this.SendPropertyChanging();
					this._ContentID = value;
					this.SendPropertyChanged("ContentID");
					this.OnContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_ContentID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Root_ContentID
		{
			get
			{
				return this._Root_ContentID;
			}
			set
			{
				if ((this._Root_ContentID != value))
				{
					if (this._carrot_RootContent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoot_ContentIDChanging(value);
					this.SendPropertyChanging();
					this._Root_ContentID = value;
					this.SendPropertyChanged("Root_ContentID");
					this.OnRoot_ContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_ContentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Parent_ContentID
		{
			get
			{
				return this._Parent_ContentID;
			}
			set
			{
				if ((this._Parent_ContentID != value))
				{
					this.OnParent_ContentIDChanging(value);
					this.SendPropertyChanging();
					this._Parent_ContentID = value;
					this.SendPropertyChanged("Parent_ContentID");
					this.OnParent_ContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLatestVersion", DbType="Bit")]
		public System.Nullable<bool> IsLatestVersion
		{
			get
			{
				return this._IsLatestVersion;
			}
			set
			{
				if ((this._IsLatestVersion != value))
				{
					this.OnIsLatestVersionChanging(value);
					this.SendPropertyChanging();
					this._IsLatestVersion = value;
					this.SendPropertyChanged("IsLatestVersion");
					this.OnIsLatestVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleBar", DbType="VarChar(256)")]
		public string TitleBar
		{
			get
			{
				return this._TitleBar;
			}
			set
			{
				if ((this._TitleBar != value))
				{
					this.OnTitleBarChanging(value);
					this.SendPropertyChanging();
					this._TitleBar = value;
					this.SendPropertyChanged("TitleBar");
					this.OnTitleBarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavMenuText", DbType="VarChar(256)")]
		public string NavMenuText
		{
			get
			{
				return this._NavMenuText;
			}
			set
			{
				if ((this._NavMenuText != value))
				{
					this.OnNavMenuTextChanging(value);
					this.SendPropertyChanging();
					this._NavMenuText = value;
					this.SendPropertyChanged("NavMenuText");
					this.OnNavMenuTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageHead", DbType="VarChar(256)")]
		public string PageHead
		{
			get
			{
				return this._PageHead;
			}
			set
			{
				if ((this._PageHead != value))
				{
					this.OnPageHeadChanging(value);
					this.SendPropertyChanging();
					this._PageHead = value;
					this.SendPropertyChanged("PageHead");
					this.OnPageHeadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageText", DbType="VarChar(MAX)")]
		public string PageText
		{
			get
			{
				return this._PageText;
			}
			set
			{
				if ((this._PageText != value))
				{
					this.OnPageTextChanging(value);
					this.SendPropertyChanging();
					this._PageText = value;
					this.SendPropertyChanged("PageText");
					this.OnPageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftPageText", DbType="VarChar(MAX)")]
		public string LeftPageText
		{
			get
			{
				return this._LeftPageText;
			}
			set
			{
				if ((this._LeftPageText != value))
				{
					this.OnLeftPageTextChanging(value);
					this.SendPropertyChanging();
					this._LeftPageText = value;
					this.SendPropertyChanged("LeftPageText");
					this.OnLeftPageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightPageText", DbType="VarChar(MAX)")]
		public string RightPageText
		{
			get
			{
				return this._RightPageText;
			}
			set
			{
				if ((this._RightPageText != value))
				{
					this.OnRightPageTextChanging(value);
					this.SendPropertyChanging();
					this._RightPageText = value;
					this.SendPropertyChanged("RightPageText");
					this.OnRightPageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavOrder", DbType="Int")]
		public System.Nullable<int> NavOrder
		{
			get
			{
				return this._NavOrder;
			}
			set
			{
				if ((this._NavOrder != value))
				{
					this.OnNavOrderChanging(value);
					this.SendPropertyChanging();
					this._NavOrder = value;
					this.SendPropertyChanged("NavOrder");
					this.OnNavOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EditUserId
		{
			get
			{
				return this._EditUserId;
			}
			set
			{
				if ((this._EditUserId != value))
				{
					if (this._aspnet_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEditUserIdChanging(value);
					this.SendPropertyChanging();
					this._EditUserId = value;
					this.SendPropertyChanged("EditUserId");
					this.OnEditUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime NOT NULL")]
		public System.DateTime EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateFile", DbType="NVarChar(256)")]
		public string TemplateFile
		{
			get
			{
				return this._TemplateFile;
			}
			set
			{
				if ((this._TemplateFile != value))
				{
					this.OnTemplateFileChanging(value);
					this.SendPropertyChanging();
					this._TemplateFile = value;
					this.SendPropertyChanged("TemplateFile");
					this.OnTemplateFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaKeyword", DbType="VarChar(1000)")]
		public string MetaKeyword
		{
			get
			{
				return this._MetaKeyword;
			}
			set
			{
				if ((this._MetaKeyword != value))
				{
					this.OnMetaKeywordChanging(value);
					this.SendPropertyChanging();
					this._MetaKeyword = value;
					this.SendPropertyChanged("MetaKeyword");
					this.OnMetaKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="VarChar(2000)")]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this.OnMetaDescriptionChanging(value);
					this.SendPropertyChanging();
					this._MetaDescription = value;
					this.SendPropertyChanged("MetaDescription");
					this.OnMetaDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_User_carrot_Content", Storage="_aspnet_User", ThisKey="EditUserId", OtherKey="UserId", IsForeignKey=true)]
		public aspnet_User aspnet_User
		{
			get
			{
				return this._aspnet_User.Entity;
			}
			set
			{
				aspnet_User previousValue = this._aspnet_User.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_User.Entity = null;
						previousValue.carrot_Contents.Remove(this);
					}
					this._aspnet_User.Entity = value;
					if ((value != null))
					{
						value.carrot_Contents.Add(this);
						this._EditUserId = value.UserId;
					}
					else
					{
						this._EditUserId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("aspnet_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_RootContent_carrot_Content", Storage="_carrot_RootContent", ThisKey="Root_ContentID", OtherKey="Root_ContentID", IsForeignKey=true)]
		public carrot_RootContent carrot_RootContent
		{
			get
			{
				return this._carrot_RootContent.Entity;
			}
			set
			{
				carrot_RootContent previousValue = this._carrot_RootContent.Entity;
				if (((previousValue != value) 
							|| (this._carrot_RootContent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrot_RootContent.Entity = null;
						previousValue.carrot_Contents.Remove(this);
					}
					this._carrot_RootContent.Entity = value;
					if ((value != null))
					{
						value.carrot_Contents.Add(this);
						this._Root_ContentID = value.Root_ContentID;
					}
					else
					{
						this._Root_ContentID = default(System.Guid);
					}
					this.SendPropertyChanged("carrot_RootContent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_Sites")]
	public partial class carrot_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SiteID;
		
		private string _MetaKeyword;
		
		private string _MetaDescription;
		
		private string _SiteName;
		
		private string _MainURL;
		
		private bool _BlockIndex;
		
		private string _SiteFolder;
		
		private EntitySet<carrot_UserSiteMapping> _carrot_UserSiteMappings;
		
		private EntitySet<carrot_RootContent> _carrot_RootContents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    partial void OnMetaKeywordChanging(string value);
    partial void OnMetaKeywordChanged();
    partial void OnMetaDescriptionChanging(string value);
    partial void OnMetaDescriptionChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnMainURLChanging(string value);
    partial void OnMainURLChanged();
    partial void OnBlockIndexChanging(bool value);
    partial void OnBlockIndexChanged();
    partial void OnSiteFolderChanging(string value);
    partial void OnSiteFolderChanged();
    #endregion
		
		public carrot_Site()
		{
			this._carrot_UserSiteMappings = new EntitySet<carrot_UserSiteMapping>(new Action<carrot_UserSiteMapping>(this.attach_carrot_UserSiteMappings), new Action<carrot_UserSiteMapping>(this.detach_carrot_UserSiteMappings));
			this._carrot_RootContents = new EntitySet<carrot_RootContent>(new Action<carrot_RootContent>(this.attach_carrot_RootContents), new Action<carrot_RootContent>(this.detach_carrot_RootContents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaKeyword", DbType="VarChar(1000)")]
		public string MetaKeyword
		{
			get
			{
				return this._MetaKeyword;
			}
			set
			{
				if ((this._MetaKeyword != value))
				{
					this.OnMetaKeywordChanging(value);
					this.SendPropertyChanging();
					this._MetaKeyword = value;
					this.SendPropertyChanged("MetaKeyword");
					this.OnMetaKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="VarChar(2000)")]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this.OnMetaDescriptionChanging(value);
					this.SendPropertyChanging();
					this._MetaDescription = value;
					this.SendPropertyChanged("MetaDescription");
					this.OnMetaDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(256)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainURL", DbType="VarChar(256)")]
		public string MainURL
		{
			get
			{
				return this._MainURL;
			}
			set
			{
				if ((this._MainURL != value))
				{
					this.OnMainURLChanging(value);
					this.SendPropertyChanging();
					this._MainURL = value;
					this.SendPropertyChanged("MainURL");
					this.OnMainURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockIndex", DbType="Bit NOT NULL")]
		public bool BlockIndex
		{
			get
			{
				return this._BlockIndex;
			}
			set
			{
				if ((this._BlockIndex != value))
				{
					this.OnBlockIndexChanging(value);
					this.SendPropertyChanging();
					this._BlockIndex = value;
					this.SendPropertyChanged("BlockIndex");
					this.OnBlockIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteFolder", DbType="VarChar(256)")]
		public string SiteFolder
		{
			get
			{
				return this._SiteFolder;
			}
			set
			{
				if ((this._SiteFolder != value))
				{
					this.OnSiteFolderChanging(value);
					this.SendPropertyChanging();
					this._SiteFolder = value;
					this.SendPropertyChanged("SiteFolder");
					this.OnSiteFolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Site_carrot_UserSiteMapping", Storage="_carrot_UserSiteMappings", ThisKey="SiteID", OtherKey="SiteID")]
		public EntitySet<carrot_UserSiteMapping> carrot_UserSiteMappings
		{
			get
			{
				return this._carrot_UserSiteMappings;
			}
			set
			{
				this._carrot_UserSiteMappings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Site_carrot_RootContent", Storage="_carrot_RootContents", ThisKey="SiteID", OtherKey="SiteID")]
		public EntitySet<carrot_RootContent> carrot_RootContents
		{
			get
			{
				return this._carrot_RootContents;
			}
			set
			{
				this._carrot_RootContents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrot_UserSiteMappings(carrot_UserSiteMapping entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Site = this;
		}
		
		private void detach_carrot_UserSiteMappings(carrot_UserSiteMapping entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Site = null;
		}
		
		private void attach_carrot_RootContents(carrot_RootContent entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Site = this;
		}
		
		private void detach_carrot_RootContents(carrot_RootContent entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Site = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_SerialCache")]
	public partial class carrot_SerialCache : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SerialCacheID;
		
		private System.Guid _SiteID;
		
		private System.Guid _ItemID;
		
		private System.Guid _EditUserId;
		
		private string _KeyType;
		
		private string _SerializedData;
		
		private System.DateTime _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSerialCacheIDChanging(System.Guid value);
    partial void OnSerialCacheIDChanged();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    partial void OnItemIDChanging(System.Guid value);
    partial void OnItemIDChanged();
    partial void OnEditUserIdChanging(System.Guid value);
    partial void OnEditUserIdChanged();
    partial void OnKeyTypeChanging(string value);
    partial void OnKeyTypeChanged();
    partial void OnSerializedDataChanging(string value);
    partial void OnSerializedDataChanged();
    partial void OnEditDateChanging(System.DateTime value);
    partial void OnEditDateChanged();
    #endregion
		
		public carrot_SerialCache()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialCacheID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SerialCacheID
		{
			get
			{
				return this._SerialCacheID;
			}
			set
			{
				if ((this._SerialCacheID != value))
				{
					this.OnSerialCacheIDChanging(value);
					this.SendPropertyChanging();
					this._SerialCacheID = value;
					this.SendPropertyChanged("SerialCacheID");
					this.OnSerialCacheIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this.OnItemIDChanging(value);
					this.SendPropertyChanging();
					this._ItemID = value;
					this.SendPropertyChanged("ItemID");
					this.OnItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid EditUserId
		{
			get
			{
				return this._EditUserId;
			}
			set
			{
				if ((this._EditUserId != value))
				{
					this.OnEditUserIdChanging(value);
					this.SendPropertyChanging();
					this._EditUserId = value;
					this.SendPropertyChanged("EditUserId");
					this.OnEditUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyType", DbType="VarChar(256)")]
		public string KeyType
		{
			get
			{
				return this._KeyType;
			}
			set
			{
				if ((this._KeyType != value))
				{
					this.OnKeyTypeChanging(value);
					this.SendPropertyChanging();
					this._KeyType = value;
					this.SendPropertyChanged("KeyType");
					this.OnKeyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerializedData", DbType="VarChar(MAX)")]
		public string SerializedData
		{
			get
			{
				return this._SerializedData;
			}
			set
			{
				if ((this._SerializedData != value))
				{
					this.OnSerializedDataChanging(value);
					this.SendPropertyChanging();
					this._SerializedData = value;
					this.SendPropertyChanged("SerializedData");
					this.OnSerializedDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime NOT NULL")]
		public System.DateTime EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_Widget")]
	public partial class carrot_Widget : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Root_WidgetID;
		
		private System.Guid _Root_ContentID;
		
		private int _WidgetOrder;
		
		private string _PlaceholderName;
		
		private string _ControlPath;
		
		private bool _WidgetActive;
		
		private EntitySet<carrot_WidgetData> _carrot_WidgetDatas;
		
		private EntityRef<carrot_RootContent> _carrot_RootContent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoot_WidgetIDChanging(System.Guid value);
    partial void OnRoot_WidgetIDChanged();
    partial void OnRoot_ContentIDChanging(System.Guid value);
    partial void OnRoot_ContentIDChanged();
    partial void OnWidgetOrderChanging(int value);
    partial void OnWidgetOrderChanged();
    partial void OnPlaceholderNameChanging(string value);
    partial void OnPlaceholderNameChanged();
    partial void OnControlPathChanging(string value);
    partial void OnControlPathChanged();
    partial void OnWidgetActiveChanging(bool value);
    partial void OnWidgetActiveChanged();
    #endregion
		
		public carrot_Widget()
		{
			this._carrot_WidgetDatas = new EntitySet<carrot_WidgetData>(new Action<carrot_WidgetData>(this.attach_carrot_WidgetDatas), new Action<carrot_WidgetData>(this.detach_carrot_WidgetDatas));
			this._carrot_RootContent = default(EntityRef<carrot_RootContent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_WidgetID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Root_WidgetID
		{
			get
			{
				return this._Root_WidgetID;
			}
			set
			{
				if ((this._Root_WidgetID != value))
				{
					this.OnRoot_WidgetIDChanging(value);
					this.SendPropertyChanging();
					this._Root_WidgetID = value;
					this.SendPropertyChanged("Root_WidgetID");
					this.OnRoot_WidgetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_ContentID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Root_ContentID
		{
			get
			{
				return this._Root_ContentID;
			}
			set
			{
				if ((this._Root_ContentID != value))
				{
					if (this._carrot_RootContent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoot_ContentIDChanging(value);
					this.SendPropertyChanging();
					this._Root_ContentID = value;
					this.SendPropertyChanged("Root_ContentID");
					this.OnRoot_ContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidgetOrder", DbType="Int NOT NULL")]
		public int WidgetOrder
		{
			get
			{
				return this._WidgetOrder;
			}
			set
			{
				if ((this._WidgetOrder != value))
				{
					this.OnWidgetOrderChanging(value);
					this.SendPropertyChanging();
					this._WidgetOrder = value;
					this.SendPropertyChanged("WidgetOrder");
					this.OnWidgetOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceholderName", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string PlaceholderName
		{
			get
			{
				return this._PlaceholderName;
			}
			set
			{
				if ((this._PlaceholderName != value))
				{
					this.OnPlaceholderNameChanging(value);
					this.SendPropertyChanging();
					this._PlaceholderName = value;
					this.SendPropertyChanged("PlaceholderName");
					this.OnPlaceholderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlPath", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string ControlPath
		{
			get
			{
				return this._ControlPath;
			}
			set
			{
				if ((this._ControlPath != value))
				{
					this.OnControlPathChanging(value);
					this.SendPropertyChanging();
					this._ControlPath = value;
					this.SendPropertyChanged("ControlPath");
					this.OnControlPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidgetActive", DbType="Bit NOT NULL")]
		public bool WidgetActive
		{
			get
			{
				return this._WidgetActive;
			}
			set
			{
				if ((this._WidgetActive != value))
				{
					this.OnWidgetActiveChanging(value);
					this.SendPropertyChanging();
					this._WidgetActive = value;
					this.SendPropertyChanged("WidgetActive");
					this.OnWidgetActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Widget_carrot_WidgetData", Storage="_carrot_WidgetDatas", ThisKey="Root_WidgetID", OtherKey="Root_WidgetID")]
		public EntitySet<carrot_WidgetData> carrot_WidgetDatas
		{
			get
			{
				return this._carrot_WidgetDatas;
			}
			set
			{
				this._carrot_WidgetDatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_RootContent_carrot_Widget", Storage="_carrot_RootContent", ThisKey="Root_ContentID", OtherKey="Root_ContentID", IsForeignKey=true)]
		public carrot_RootContent carrot_RootContent
		{
			get
			{
				return this._carrot_RootContent.Entity;
			}
			set
			{
				carrot_RootContent previousValue = this._carrot_RootContent.Entity;
				if (((previousValue != value) 
							|| (this._carrot_RootContent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrot_RootContent.Entity = null;
						previousValue.carrot_Widgets.Remove(this);
					}
					this._carrot_RootContent.Entity = value;
					if ((value != null))
					{
						value.carrot_Widgets.Add(this);
						this._Root_ContentID = value.Root_ContentID;
					}
					else
					{
						this._Root_ContentID = default(System.Guid);
					}
					this.SendPropertyChanged("carrot_RootContent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrot_WidgetDatas(carrot_WidgetData entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Widget = this;
		}
		
		private void detach_carrot_WidgetDatas(carrot_WidgetData entity)
		{
			this.SendPropertyChanging();
			entity.carrot_Widget = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_RootContent")]
	public partial class carrot_RootContent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Root_ContentID;
		
		private System.Guid _SiteID;
		
		private System.Nullable<System.Guid> _Heartbeat_UserId;
		
		private System.Nullable<System.DateTime> _EditHeartbeat;
		
		private string _FileName;
		
		private bool _PageActive;
		
		private System.DateTime _CreateDate;
		
		private EntitySet<carrot_Content> _carrot_Contents;
		
		private EntitySet<carrot_Widget> _carrot_Widgets;
		
		private EntityRef<carrot_Site> _carrot_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoot_ContentIDChanging(System.Guid value);
    partial void OnRoot_ContentIDChanged();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    partial void OnHeartbeat_UserIdChanging(System.Nullable<System.Guid> value);
    partial void OnHeartbeat_UserIdChanged();
    partial void OnEditHeartbeatChanging(System.Nullable<System.DateTime> value);
    partial void OnEditHeartbeatChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnPageActiveChanging(bool value);
    partial void OnPageActiveChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
		
		public carrot_RootContent()
		{
			this._carrot_Contents = new EntitySet<carrot_Content>(new Action<carrot_Content>(this.attach_carrot_Contents), new Action<carrot_Content>(this.detach_carrot_Contents));
			this._carrot_Widgets = new EntitySet<carrot_Widget>(new Action<carrot_Widget>(this.attach_carrot_Widgets), new Action<carrot_Widget>(this.detach_carrot_Widgets));
			this._carrot_Site = default(EntityRef<carrot_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_ContentID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Root_ContentID
		{
			get
			{
				return this._Root_ContentID;
			}
			set
			{
				if ((this._Root_ContentID != value))
				{
					this.OnRoot_ContentIDChanging(value);
					this.SendPropertyChanging();
					this._Root_ContentID = value;
					this.SendPropertyChanged("Root_ContentID");
					this.OnRoot_ContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					if (this._carrot_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heartbeat_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Heartbeat_UserId
		{
			get
			{
				return this._Heartbeat_UserId;
			}
			set
			{
				if ((this._Heartbeat_UserId != value))
				{
					this.OnHeartbeat_UserIdChanging(value);
					this.SendPropertyChanging();
					this._Heartbeat_UserId = value;
					this.SendPropertyChanged("Heartbeat_UserId");
					this.OnHeartbeat_UserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditHeartbeat", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditHeartbeat
		{
			get
			{
				return this._EditHeartbeat;
			}
			set
			{
				if ((this._EditHeartbeat != value))
				{
					this.OnEditHeartbeatChanging(value);
					this.SendPropertyChanging();
					this._EditHeartbeat = value;
					this.SendPropertyChanged("EditHeartbeat");
					this.OnEditHeartbeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageActive", DbType="Bit NOT NULL")]
		public bool PageActive
		{
			get
			{
				return this._PageActive;
			}
			set
			{
				if ((this._PageActive != value))
				{
					this.OnPageActiveChanging(value);
					this.SendPropertyChanging();
					this._PageActive = value;
					this.SendPropertyChanged("PageActive");
					this.OnPageActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_RootContent_carrot_Content", Storage="_carrot_Contents", ThisKey="Root_ContentID", OtherKey="Root_ContentID")]
		public EntitySet<carrot_Content> carrot_Contents
		{
			get
			{
				return this._carrot_Contents;
			}
			set
			{
				this._carrot_Contents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_RootContent_carrot_Widget", Storage="_carrot_Widgets", ThisKey="Root_ContentID", OtherKey="Root_ContentID")]
		public EntitySet<carrot_Widget> carrot_Widgets
		{
			get
			{
				return this._carrot_Widgets;
			}
			set
			{
				this._carrot_Widgets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Site_carrot_RootContent", Storage="_carrot_Site", ThisKey="SiteID", OtherKey="SiteID", IsForeignKey=true)]
		public carrot_Site carrot_Site
		{
			get
			{
				return this._carrot_Site.Entity;
			}
			set
			{
				carrot_Site previousValue = this._carrot_Site.Entity;
				if (((previousValue != value) 
							|| (this._carrot_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrot_Site.Entity = null;
						previousValue.carrot_RootContents.Remove(this);
					}
					this._carrot_Site.Entity = value;
					if ((value != null))
					{
						value.carrot_RootContents.Add(this);
						this._SiteID = value.SiteID;
					}
					else
					{
						this._SiteID = default(System.Guid);
					}
					this.SendPropertyChanged("carrot_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrot_Contents(carrot_Content entity)
		{
			this.SendPropertyChanging();
			entity.carrot_RootContent = this;
		}
		
		private void detach_carrot_Contents(carrot_Content entity)
		{
			this.SendPropertyChanging();
			entity.carrot_RootContent = null;
		}
		
		private void attach_carrot_Widgets(carrot_Widget entity)
		{
			this.SendPropertyChanging();
			entity.carrot_RootContent = this;
		}
		
		private void detach_carrot_Widgets(carrot_Widget entity)
		{
			this.SendPropertyChanging();
			entity.carrot_RootContent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrot_WidgetData")]
	public partial class carrot_WidgetData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _WidgetDataID;
		
		private System.Guid _Root_WidgetID;
		
		private System.Nullable<bool> _IsLatestVersion;
		
		private System.DateTime _EditDate;
		
		private string _ControlProperties;
		
		private EntityRef<carrot_Widget> _carrot_Widget;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWidgetDataIDChanging(System.Guid value);
    partial void OnWidgetDataIDChanged();
    partial void OnRoot_WidgetIDChanging(System.Guid value);
    partial void OnRoot_WidgetIDChanged();
    partial void OnIsLatestVersionChanging(System.Nullable<bool> value);
    partial void OnIsLatestVersionChanged();
    partial void OnEditDateChanging(System.DateTime value);
    partial void OnEditDateChanged();
    partial void OnControlPropertiesChanging(string value);
    partial void OnControlPropertiesChanged();
    #endregion
		
		public carrot_WidgetData()
		{
			this._carrot_Widget = default(EntityRef<carrot_Widget>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidgetDataID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid WidgetDataID
		{
			get
			{
				return this._WidgetDataID;
			}
			set
			{
				if ((this._WidgetDataID != value))
				{
					this.OnWidgetDataIDChanging(value);
					this.SendPropertyChanging();
					this._WidgetDataID = value;
					this.SendPropertyChanged("WidgetDataID");
					this.OnWidgetDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_WidgetID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Root_WidgetID
		{
			get
			{
				return this._Root_WidgetID;
			}
			set
			{
				if ((this._Root_WidgetID != value))
				{
					if (this._carrot_Widget.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoot_WidgetIDChanging(value);
					this.SendPropertyChanging();
					this._Root_WidgetID = value;
					this.SendPropertyChanged("Root_WidgetID");
					this.OnRoot_WidgetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLatestVersion", DbType="Bit")]
		public System.Nullable<bool> IsLatestVersion
		{
			get
			{
				return this._IsLatestVersion;
			}
			set
			{
				if ((this._IsLatestVersion != value))
				{
					this.OnIsLatestVersionChanging(value);
					this.SendPropertyChanging();
					this._IsLatestVersion = value;
					this.SendPropertyChanged("IsLatestVersion");
					this.OnIsLatestVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime NOT NULL")]
		public System.DateTime EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlProperties", DbType="VarChar(MAX)")]
		public string ControlProperties
		{
			get
			{
				return this._ControlProperties;
			}
			set
			{
				if ((this._ControlProperties != value))
				{
					this.OnControlPropertiesChanging(value);
					this.SendPropertyChanging();
					this._ControlProperties = value;
					this.SendPropertyChanged("ControlProperties");
					this.OnControlPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="carrot_Widget_carrot_WidgetData", Storage="_carrot_Widget", ThisKey="Root_WidgetID", OtherKey="Root_WidgetID", IsForeignKey=true)]
		public carrot_Widget carrot_Widget
		{
			get
			{
				return this._carrot_Widget.Entity;
			}
			set
			{
				carrot_Widget previousValue = this._carrot_Widget.Entity;
				if (((previousValue != value) 
							|| (this._carrot_Widget.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._carrot_Widget.Entity = null;
						previousValue.carrot_WidgetDatas.Remove(this);
					}
					this._carrot_Widget.Entity = value;
					if ((value != null))
					{
						value.carrot_WidgetDatas.Add(this);
						this._Root_WidgetID = value.Root_WidgetID;
					}
					else
					{
						this._Root_WidgetID = default(System.Guid);
					}
					this.SendPropertyChanged("carrot_Widget");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_carrot_Content")]
	public partial class vw_carrot_Content
	{
		
		private System.Guid _Root_ContentID;
		
		private System.Guid _SiteID;
		
		private System.Nullable<System.Guid> _Heartbeat_UserId;
		
		private System.Nullable<System.DateTime> _EditHeartbeat;
		
		private string _FileName;
		
		private bool _PageActive;
		
		private System.DateTime _CreateDate;
		
		private System.Guid _ContentID;
		
		private System.Nullable<System.Guid> _Parent_ContentID;
		
		private System.Nullable<bool> _IsLatestVersion;
		
		private string _TitleBar;
		
		private string _NavMenuText;
		
		private string _PageHead;
		
		private string _PageText;
		
		private string _LeftPageText;
		
		private string _RightPageText;
		
		private System.Nullable<int> _NavOrder;
		
		private System.Nullable<System.Guid> _EditUserId;
		
		private System.DateTime _EditDate;
		
		private string _TemplateFile;
		
		private string _MetaKeyword;
		
		private string _MetaDescription;
		
		public vw_carrot_Content()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Root_ContentID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Root_ContentID
		{
			get
			{
				return this._Root_ContentID;
			}
			set
			{
				if ((this._Root_ContentID != value))
				{
					this._Root_ContentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this._SiteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heartbeat_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Heartbeat_UserId
		{
			get
			{
				return this._Heartbeat_UserId;
			}
			set
			{
				if ((this._Heartbeat_UserId != value))
				{
					this._Heartbeat_UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditHeartbeat", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditHeartbeat
		{
			get
			{
				return this._EditHeartbeat;
			}
			set
			{
				if ((this._EditHeartbeat != value))
				{
					this._EditHeartbeat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageActive", DbType="Bit NOT NULL")]
		public bool PageActive
		{
			get
			{
				return this._PageActive;
			}
			set
			{
				if ((this._PageActive != value))
				{
					this._PageActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ContentID
		{
			get
			{
				return this._ContentID;
			}
			set
			{
				if ((this._ContentID != value))
				{
					this._ContentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_ContentID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Parent_ContentID
		{
			get
			{
				return this._Parent_ContentID;
			}
			set
			{
				if ((this._Parent_ContentID != value))
				{
					this._Parent_ContentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLatestVersion", DbType="Bit")]
		public System.Nullable<bool> IsLatestVersion
		{
			get
			{
				return this._IsLatestVersion;
			}
			set
			{
				if ((this._IsLatestVersion != value))
				{
					this._IsLatestVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleBar", DbType="VarChar(256)")]
		public string TitleBar
		{
			get
			{
				return this._TitleBar;
			}
			set
			{
				if ((this._TitleBar != value))
				{
					this._TitleBar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavMenuText", DbType="VarChar(256)")]
		public string NavMenuText
		{
			get
			{
				return this._NavMenuText;
			}
			set
			{
				if ((this._NavMenuText != value))
				{
					this._NavMenuText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageHead", DbType="VarChar(256)")]
		public string PageHead
		{
			get
			{
				return this._PageHead;
			}
			set
			{
				if ((this._PageHead != value))
				{
					this._PageHead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageText", DbType="VarChar(MAX)")]
		public string PageText
		{
			get
			{
				return this._PageText;
			}
			set
			{
				if ((this._PageText != value))
				{
					this._PageText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeftPageText", DbType="VarChar(MAX)")]
		public string LeftPageText
		{
			get
			{
				return this._LeftPageText;
			}
			set
			{
				if ((this._LeftPageText != value))
				{
					this._LeftPageText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightPageText", DbType="VarChar(MAX)")]
		public string RightPageText
		{
			get
			{
				return this._RightPageText;
			}
			set
			{
				if ((this._RightPageText != value))
				{
					this._RightPageText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavOrder", DbType="Int")]
		public System.Nullable<int> NavOrder
		{
			get
			{
				return this._NavOrder;
			}
			set
			{
				if ((this._NavOrder != value))
				{
					this._NavOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> EditUserId
		{
			get
			{
				return this._EditUserId;
			}
			set
			{
				if ((this._EditUserId != value))
				{
					this._EditUserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime NOT NULL")]
		public System.DateTime EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this._EditDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateFile", DbType="NVarChar(256)")]
		public string TemplateFile
		{
			get
			{
				return this._TemplateFile;
			}
			set
			{
				if ((this._TemplateFile != value))
				{
					this._TemplateFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaKeyword", DbType="VarChar(1000)")]
		public string MetaKeyword
		{
			get
			{
				return this._MetaKeyword;
			}
			set
			{
				if ((this._MetaKeyword != value))
				{
					this._MetaKeyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="VarChar(2000)")]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this._MetaDescription = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
