ALTER TABLE [dbo].[carrot_WidgetData]
    ADD CONSTRAINT [PK_carrot_WidgetData] PRIMARY KEY CLUSTERED ([WidgetDataID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
