ALTER TABLE [dbo].[carrot_TrackbackQueue]
    ADD CONSTRAINT [PK_carrot_TrackbackQueue] PRIMARY KEY NONCLUSTERED ([TrackbackQueueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

