ALTER TABLE [dbo].[carrot_TagContentMapping]
    ADD CONSTRAINT [PK_carrot_TagContentMapping] PRIMARY KEY NONCLUSTERED ([TagContentMappingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];
