ALTER TABLE [dbo].[carrot_CategoryContentMapping]
    ADD CONSTRAINT [PK_carrot_CategoryContentMapping] PRIMARY KEY NONCLUSTERED ([CategoryContentMappingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

