ALTER TABLE [dbo].[carrot_ContentSnippet]
    ADD CONSTRAINT [PK_carrot_ContentSnippet] PRIMARY KEY CLUSTERED ([ContentSnippetID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

