ALTER TABLE [dbo].[carrot_RootContentSnippet]
    ADD CONSTRAINT [PK_carrot_RootContentSnippet] PRIMARY KEY CLUSTERED ([Root_ContentSnippetID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

