ALTER TABLE [dbo].[tblFAQ]
    ADD CONSTRAINT [tblFAQ_PK_UC1] PRIMARY KEY CLUSTERED ([FaqID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

