ALTER TABLE [dbo].[carrot_Widget]
    ADD CONSTRAINT [PK_carrot_Widget] PRIMARY KEY CLUSTERED ([Root_WidgetID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

