ALTER TABLE [dbo].[carrot_RootContent]
    ADD CONSTRAINT [carrot_RootContent_PK] PRIMARY KEY CLUSTERED ([Root_ContentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

