//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrotware.CMS.UI.Plugins.PhotoGallery {
    
    
    public partial class PhotoGalleryTest {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// jquerybasic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.Web.UI.Controls.jquerybasic jquerybasic;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// GalleryFancyBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.PhotoGallery.PhotoGalleryFancyBox GalleryFancyBox1;
        
        /// <summary>
        /// GalleryFancyBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.PhotoGallery.PhotoGalleryFancyBox2 GalleryFancyBox2;
        
        /// <summary>
        /// PhotoGalleryAdminCategoryList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.PhotoGallery.PhotoGalleryAdminCategoryList PhotoGalleryAdminCategoryList1;
        
        /// <summary>
        /// PhotoGalleryAdmin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.PhotoGallery.PhotoGalleryAdmin PhotoGalleryAdmin1;
        
        /// <summary>
        /// PhotoGalleryAdminCategory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.PhotoGallery.PhotoGalleryAdminCategory PhotoGalleryAdminCategory1;
    }
}
