//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrotware.CMS.UI.Plugins.CalendarModule {
    
    
    public partial class WebForm3 {
        
        /// <summary>
        /// ucCalendarDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.CMS.UI.Plugins.CalendarModule.CalendarDisplay ucCalendarDisplay;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Carrotware.CMS.UI.Plugins.CalendarModule.Site1 Master {
            get {
                return ((Carrotware.CMS.UI.Plugins.CalendarModule.Site1)(base.Master));
            }
        }
    }
}
