//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrotware.CMS.UI.Admin.c3_admin {
    
    
    public partial class UserGroups {
        
        /// <summary>
        /// gvRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Carrotware.Web.UI.Controls.CarrotGridView gvRoles;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Carrotware.CMS.UI.Admin.c3_admin.MasterPages.Main Master {
            get {
                return ((Carrotware.CMS.UI.Admin.c3_admin.MasterPages.Main)(base.Master));
            }
        }
    }
}
