ALTER TABLE [dbo].[carrot_Content]
    ADD CONSTRAINT [PK_carrot_Content] PRIMARY KEY CLUSTERED ([ContentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

