//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrotware.CMS.UI.Base {
    
    
    public partial class GenericPageFromMaster {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Carrotware.CMS.UI.Base.GenericMasterPage Master {
            get {
                return ((Carrotware.CMS.UI.Base.GenericMasterPage)(base.Master));
            }
        }
    }
}
